### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by magnusnissel** [danielfaulknor/TweetDeleter#1]
I saw you've added some nice tweaks to the original, which was under the "Unlicense". I couldn't find any license information on your fork. I'm asking because I'd like to fork & extend (or rather, specialize to my specific needs).

**Comment by danielfaulknor** [comment]
Unlicense it is!

I'd love to see what changes you make though!

**Comment by magnusnissel** [comment]
Sure, feel free to check over at https://github.com/magnusnissel/tweetdeleter
Still have a few things to implement (tweet backup before deletion, not all arguments are parsed/loaded from config yet). May add a GUI script.

**Comment by danielfaulknor** [comment]
Very nice! 

I use this to backup my tweets - https://github.com/danielfaulknor/ozh-tweet-archiver
